# If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Susanna Allés Torrent
author: Susanna Allés Torrent
email: susanna_alles@miami.edu
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://susannalles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sallesto
github_username:  susannalles
googlescholar_username: Susanna Allés Torrent

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

include:
  - assets

exclude:
  - Gemfile
  - Gemfile.lock

#gems: [jekyll-paginate]
#paginate: 5
#paginate_pathe: "blog/page:num/"
#Create a collection:
collections:
  materials:
    output: true

categories:
   workshops
   conferences
   
