highlighter: true
markdown: kramdown
url: https://github.com/susannalles/susannalles.github.io/tree/master/Vitae
permalink: none

# Required if you want to move pages into a a separate directory
# not working at the moment for some reason
include: ['_manuscripts/']
